const CONFIG = {
    titleWeb: "duogjeg web",
    introTitle: 'du er en idiot, men du er min idiot',
    introDesc: 'der må være en grund til vibaltid finder tilbage til hinanden gang på gang`,
    btnIntro: '^^HiHi^^',
    title: 'Did I fall in love at first sight 🥰',
    desc: 'Maybe I was drunk from the moment I saw that smile',
    btnYes: 'I like you very much <33',
    btnNo: 'No:3',
    question: 'There are more than 7 billion people in the world, why do you love me <3',
    btnReply: 'Sent to you <3',
    reply: 'If you love, you love <33333333',
    mess: 'Love you so much 😘😘',
    messDesc: 'Tonight me and you🥰.',
    btnAccept: 'Okay love? <3',
    messLink: 'https://github.com/love/Confess-Crush'
